### ISSUE TITLE
AdmitsFinitelyManyNontips not working correctly?

### ISSUE THREAD

**Issue by erich-9** [gap-packages/qpa#28]
There seems to be another issue with the routines for Groebner bases (not related to GBNP and #20).

For example, the code
```
Q := Quiver(1, [[1,1,"a"],[1,1,"b"]]);
KQ := PathAlgebra(Rationals, Q);
AssignGeneratorVariables(KQ);

rels := [ a*b+b*a+b^2+b^2*a, a^2+a*b+b*a+b^2+b^3 ];

gb_gbnp := GBNPGroebnerBasis(rels, KQ);
I := Ideal(KQ, gb_gbnp);
gb := GroebnerBasis(I, gb_gbnp);

A := KQ/I;

if IsFiniteDimensional(A) then
  Print("dim(A) = ", Dimension(A), "\n");
  P := IndecProjectiveModules(A);
fi;
```
produces with `QPA 1.27` and `1.29` the error message:
```
dim(A) = 11
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 2nd choice method found for `IndecProjectiveModules' on 1 arguments at /usr/lib/gap/lib/methsel2.g:250 called from
```
I think the problem is that `A` is erroneously found to be finite dimensional.

**Comment by sunnyquiver** [comment]
I think that this is a problem with GBNP.  It seems that GBNP is computing something it thinks is a Groebner basis, while the command <C>HighLevelGroebnerBasis</C> seemingly enters an infinitely long computation (at least it didn't terminate within 3 minutes).  This leads me to believe that the ideal doesn't have a finite Groebner basis.  I have not checked this by hand.  So maybe this is another example where GBNP fails to compute the correct Groebner basis of an ideal. 

When <C>IndecProjectiveModules</C> is called it checks if the algebra <Arg>A</Arg> satisfies <C>IsAdmissibleQuotientOfPathAlgebra(A)</C>, which this algebra doesn't satisfies with the possibly wrong Groebner basis computed by <pkg>GBNP</pkg>. Therefore it starts to search for another method.  

So I think that one needs to check if this ideal has a finite Groebner basis or not by hand to get to the bottom of this problem/issue.

**Comment by sunnyquiver** [comment]
Entering this example into QPA2 and computing a Groebner basis takes approximately 5 seconds, and it computes a Groebner basis with the same number of elements as GBNP.  The one from GBNP might be tipreduced, while the one from QPA2 is not.  But since both of them produce a finite Groebner basis, this ideal most likely has a finite Groebner basis.  The command <C>AdmitsFinitelyManyNontips(gb)</C> gives the right answer.  However, the ideal generated by rels is not admissible, so that the algebra has not only one indecomposable projective module, but two. The algebra modulo the radical is the direct sum two fields, Rationals and Rationals[x]/(x^3 - x^2 - 9x - 1). If the command IndecProjectiveModules(A) would be successful, it would only find one indecomposable projective module.  So I think all is what is should be.

**Comment by erich-9** [comment]
You are completely right. The Groebner basis computed by GBNP and the result of AdmitsFinitelyManyNontips are both correct. So there is no problem and I am closing this issue.

Thank you very much for the detailed explanations and sorry for my mistake.
